name: 🐛 Bug Report
description: Report a bug or issue with Console Log Pipe
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - "@kansnpms/console-log-pipe-client (Browser client)"
        - "console-log-pipe (CLI tool)"
        - "@kansnpms/console-log-pipe-server (Server)"
        - "@kansnpms/console-log-pipe-desktop (Desktop app)"
        - "Browser Extension"
        - "Documentation"
        - "Other"
      default: 0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., macOS 13.0, Windows 11, Ubuntu 22.04]
        - Browser: [e.g., Chrome 115, Firefox 116, Safari 16]
        - Node.js version: [e.g., 18.17.0]
        - Package manager: [e.g., npm 9.6.7, yarn 1.22.19]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or console output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to fixing this issue?
      options:
        - label: I would like to work on fixing this issue
        - label: I can provide additional testing or feedback
